<h1 align='center'> Neural Network from Scratch </h1>
<h3 align='center'> Creating Batches and Layers </h3>

In [1]:
import numpy as np

### Why Batch? 
This will help perform more parallel operations. Because showing the model 1 sample at a time helps the best fit line fit faster.

### What will happen if we fit all the Data at once?
This can lead to over-fitting. This can hurt your Neural Network.  

**The most common Batch Size is equal to 32.**

## Dot product of a 1 Layer of Neurons

In [2]:
inputs = [[1, 2, 3, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]

### We don't need to change anything in our Weights and Bias as they are uniquely associated with the neuron.
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

Here the weights and inputs are the same shape. So they will give an error (shape error).
- Using np.shape() we see that shape of Weights and Inputs are (3,4) --> It is a 3x4 matrix.

> - Now for Matrix multiplication the number if Columns of the 1st Matrix should be equal to the number of Rows of the 2nd.
> - For this we use the concept of transpose. This is simply switching the rows in a martix to the column.

***For performing Transpose we will convert Weights to numpy array.***

In [3]:
output1 = np.dot(inputs, np.array(weights).T) + biases      
print(output1)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## Dot product of a 2 Layer of Neurons

In [4]:
inputs = [[1, 2, 3, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]

### Layer 1
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]


### Layer 2
weights2 = [[0.1, -0.14, 0.5], 
           [-0.5, 0.12, -0.33], 
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

In [6]:
layer1_output = np.dot(inputs, np.array(weights).T) + biases     
print('This is Layer 1 output \n',layer1_output)

This is Layer 1 output 
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


**This Output becomes the inputs for Layer 2.**

In [7]:
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2  
print('This is Layer 2 output \n',layer2_output)

This is Layer 2 output 
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


### **Rather than doing all this, we will convert these to objects.**

In [8]:
np.random.seed(0)       ## Setting a random seed

In [9]:
## Input Data
X = [[1, 2, 3, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]

# Hidden Layers
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)   ## For this we need to know the size of the inputs coming in and the size of the neurons in the hidden layer.
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

- We will initialize weights to be in between [-1,1] and bias to be 0(Not always recommended). 
- This is so that the value (XW+b) is not too high.

> ***np.random.randn --> generates Gaussian values.***

In [10]:
layer1 = Layer_Dense(4,5)   ## (n_inputs= 4, n_neurons= 5)
layer2 = Layer_Dense(5,2)   ## The output from layer1 should be the input.

In [11]:
layer1.forward(X)
print(layer1.output)        ## This becomes the input for layer2.

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [12]:
layer2.forward(layer1.output)
print(layer2.output)        

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


> We get a 3x2 matrix --> **3x4.4x5.5x2 = 3x2**